import * as THREE from 'three'; import { COLORS } from '../core/Config'; import { BOXING_GLOVE, type WeaponDefinition } from './Weapon';
type PunchPhase = 'idle' | 'windup' | 'strike' | 'impact' | 'return';
export class Fist {
  readonly definition: WeaponDefinition = BOXING_GLOVE; readonly group = new THREE.Group(); phase: PunchPhase = 'idle';
  private readonly idle = new THREE.Vector3(.2, -.83, -1.95); private readonly windup = new THREE.Vector3(.28, -.96, -1.55); private target = new THREE.Vector3(); private phaseTime = 0; private totalTime = 0; private impacted = false; private onImpact?: () => void; private onComplete?: () => void;
  constructor(private camera: THREE.PerspectiveCamera) { const red = new THREE.MeshStandardMaterial({ color: COLORS.glove, roughness: .58 }); const dark = new THREE.MeshStandardMaterial({ color: COLORS.gloveDark, roughness: .72 }); const palm = new THREE.Mesh(new THREE.SphereGeometry(.34, 18, 13), red); palm.scale.set(1.05, .9, 1.15); palm.castShadow = true; this.group.add(palm); for (let i = 0; i < 4; i++) { const knuckle = new THREE.Mesh(new THREE.SphereGeometry(.145, 12, 8), red); knuckle.position.set((i - 1.5) * .16, .17, -.11); knuckle.castShadow = true; this.group.add(knuckle); } const cuff = new THREE.Mesh(new THREE.CylinderGeometry(.27, .32, .38, 14), dark); cuff.rotation.x = Math.PI / 2; cuff.position.z = .36; this.group.add(cuff); this.group.position.copy(this.idle); this.group.rotation.set(-.18, -.12, .03); this.group.scale.setScalar(.82); camera.add(this.group); }
  punch(worldTarget: THREE.Vector3, onImpact: () => void, onComplete: () => void): boolean { if (this.phase !== 'idle') return false; this.target.copy(this.camera.worldToLocal(worldTarget.clone())); this.target.z += .28; this.onImpact = onImpact; this.onComplete = onComplete; this.phase = 'windup'; this.phaseTime = 0; this.impacted = false; return true; }
  update(delta: number): void { this.totalTime += delta; this.phaseTime += delta; if (this.phase === 'idle') { this.group.position.copy(this.idle); this.group.position.y += Math.sin(this.totalTime * 2.2) * .025; this.group.rotation.z = Math.sin(this.totalTime * 1.7) * .025; return; } if (this.phase === 'windup') { this.group.position.lerpVectors(this.idle, this.windup, this.ease(this.phaseTime / .075)); if (this.phaseTime >= .075) this.next('strike'); } else if (this.phase === 'strike') { this.group.position.lerpVectors(this.windup, this.target, this.ease(this.phaseTime / .115)); this.group.rotation.x = -.05; if (this.phaseTime >= .115) this.next('impact'); } else if (this.phase === 'impact') { if (!this.impacted) { this.impacted = true; this.onImpact?.(); } if (this.phaseTime >= .045) this.next('return'); } else if (this.phase === 'return') { this.group.position.lerpVectors(this.target, this.idle, this.ease(this.phaseTime / .21)); if (this.phaseTime >= .21) { this.phase = 'idle'; this.phaseTime = 0; this.onComplete?.(); } } }
  private next(phase: PunchPhase): void { this.phase = phase; this.phaseTime = 0; } private ease(value: number): number { const t = THREE.MathUtils.clamp(value, 0, 1); return 1 - Math.pow(1 - t, 3); }
}
