import * as THREE from 'three'; import RAPIER from '@dimforge/rapier3d-compat'; import { GAME_PHYSICS } from '../core/Config'; import { AnimalModelFactory } from './AnimalModelFactory'; import { AnimalState, type AnimalDefinition, type AnimalPartName } from './AnimalDefinition';
export interface RagdollPart { name: AnimalPartName; visual: THREE.Group; body: RAPIER.RigidBody; collider: RAPIER.Collider; meshes: THREE.Mesh[]; }
export class RagdollAnimal {
  readonly group = new THREE.Group(); readonly parts = new Map<AnimalPartName, RagdollPart>(); readonly targets: THREE.Mesh[] = []; readonly colliders = new Map<number, RagdollPart>(); state = AnimalState.Idle; chainId?: number; maxDistance = 0;
  get visible(): boolean { return this.group.visible; }
  private joints: RAPIER.ImpulseJoint[] = []; private elapsed = 0; private ragdollAt = 0; private materials: THREE.Material[]; private origin: THREE.Vector3;
  constructor(private scene: THREE.Scene, private world: RAPIER.World, readonly definition: AnimalDefinition, position: [number, number, number], readonly instanceId: string, private powerMultiplier = 1) { this.origin = new THREE.Vector3(...position); const model = AnimalModelFactory.create(definition); this.materials = model.materials; this.pendingVisuals = model.visuals; scene.add(this.group); this.buildParts(model.visuals); this.pendingVisuals = undefined; this.buildJoints(); this.syncVisuals(); }
  private buildParts(visuals: Map<AnimalPartName, THREE.Group>): void {
    this.addPart('torso',[0,2.35,0],visuals.get('torso')!,RAPIER.ColliderDesc.capsule(.34*this.scale,.4*this.scale)); this.addPart('hips',[0,1.72,0],visuals.get('hips')!,RAPIER.ColliderDesc.cuboid(.39*this.scale,.24*this.scale,.31*this.scale)); this.addPart('head',[0,3.12,0],visuals.get('head')!,RAPIER.ColliderDesc.ball(.48*this.scale));
    this.addLimb('leftUpperArm',[-.67,2.37,0],.5,.145); this.addLimb('rightUpperArm',[.67,2.37,0],.5,.145); this.addLimb('leftLowerArm',[-.83,1.91,.02],.45,.13); this.addLimb('rightLowerArm',[.83,1.91,.02],.45,.13); this.addLimb('leftUpperLeg',[-.29,1.25,0],.48,.17); this.addLimb('rightUpperLeg',[.29,1.25,0],.48,.17); this.addLimb('leftLowerLeg',[-.31,.68,.02],.5,.16); this.addLimb('rightLowerLeg',[.31,.68,.02],.5,.16);
  }
  private get scale(): number { return this.definition.scale; }
  private addLimb(name: AnimalPartName, local: [number,number,number], length: number, radius: number): void { const limbScale = this.definition.id === 'frog' ? 1.25 : this.definition.id === 'chicken' ? .72 : 1; this.addPart(name,local,this.findVisual(name),RAPIER.ColliderDesc.capsule(length*limbScale*this.scale/2,radius*limbScale*this.scale)); }
  private findVisual(name: AnimalPartName): THREE.Group { const existing = this.pendingVisuals?.get(name); if (!existing) throw new Error(`Missing visual ${name}`); return existing; }
  private pendingVisuals?: Map<AnimalPartName, THREE.Group>;
  private addPart(name: AnimalPartName, local: [number,number,number], visual: THREE.Group, colliderDesc: RAPIER.ColliderDesc): void {
    const p = new THREE.Vector3(...local).multiplyScalar(this.scale).add(this.origin); visual.scale.multiplyScalar(this.scale); const body = this.world.createRigidBody(RAPIER.RigidBodyDesc.fixed().setTranslation(p.x,p.y,p.z).setLinearDamping(.55).setAngularDamping(.65)); colliderDesc.setDensity(1.15*this.definition.massMultiplier).setRestitution(.38*this.definition.bounceMultiplier).setFriction(.78); const collider = this.world.createCollider(colliderDesc,body); const meshes: THREE.Mesh[]=[]; visual.traverse(object=>{if(object instanceof THREE.Mesh){object.castShadow=true;object.receiveShadow=true;object.userData.animalPart=name;object.userData.animal=this;this.targets.push(object);meshes.push(object);}}); this.group.add(visual); const part={name,visual,body,collider,meshes}; this.parts.set(name,part);this.colliders.set(collider.handle,part);
  }
  private buildJoints():void{this.joint('torso','head',[0,.48,0],[0,-.42,0]);this.joint('torso','hips',[0,-.48,0],[0,.28,0]);this.joint('torso','leftUpperArm',[-.48,.2,0],[.12,.25,0]);this.joint('torso','rightUpperArm',[.48,.2,0],[-.12,.25,0]);this.joint('leftUpperArm','leftLowerArm',[-.08,-.25,0],[.05,.22,0]);this.joint('rightUpperArm','rightLowerArm',[.08,-.25,0],[-.05,.22,0]);this.joint('hips','leftUpperLeg',[-.25,-.18,0],[0,.27,0]);this.joint('hips','rightUpperLeg', [.25,-.18,0],[0,.27,0]);this.joint('leftUpperLeg','leftLowerLeg',[0,-.27,0],[0,.27,0]);this.joint('rightUpperLeg','rightLowerLeg',[0,-.27,0],[0,.27,0]);}
  private joint(a:AnimalPartName,b:AnimalPartName,aa:[number,number,number],ab:[number,number,number]):void{const s=this.scale;const data=RAPIER.JointData.spherical({x:aa[0]*s,y:aa[1]*s,z:aa[2]*s},{x:ab[0]*s,y:ab[1]*s,z:ab[2]*s});this.joints.push(this.world.createImpulseJoint(data,this.parts.get(a)!.body,this.parts.get(b)!.body,true));}
  private activate(chainId:number):void{if(this.state!==AnimalState.Idle)return;this.state=AnimalState.Hit;this.chainId=chainId;for(const part of this.parts.values())part.body.setBodyType(RAPIER.RigidBodyType.Dynamic,true);this.state=AnimalState.Ragdoll;this.ragdollAt=this.elapsed;}
  hit(partName:AnimalPartName,point:THREE.Vector3,direction:THREE.Vector3,chainId:number):number{if(this.state!==AnimalState.Idle)return 0;this.activate(chainId);const target=this.parts.get(partName)!;const m=partName==='head'?1.5:partName==='torso'||partName==='hips'?1.18:.92;const impulse=direction.clone().normalize().multiplyScalar(GAME_PHYSICS.punchPower*this.powerMultiplier*this.definition.launchMultiplier*m);if(partName.includes('Leg'))impulse.y-=1.5;else impulse.y+=partName==='head'?2.2:.65;target.body.applyImpulseAtPoint(impulse,point,true);const side=point.x>=this.origin.x?-1:1;target.body.applyTorqueImpulse({x:partName==='head'?1.2:.25,y:side*m,z:side*2.1*GAME_PHYSICS.angularMultiplier},true);return Math.round(100*m);}
  knockdown(partName:AnimalPartName,impulse:THREE.Vector3,chainId:number):boolean{if(this.state!==AnimalState.Idle)return false;this.activate(chainId);const target=this.parts.get(partName)!;target.body.applyImpulse({x:impulse.x*this.definition.launchMultiplier,y:Math.max(.4,impulse.y),z:impulse.z*this.definition.launchMultiplier},true);target.body.applyTorqueImpulse({x:impulse.z*.25,y:impulse.x*.2,z:-impulse.x*.35},true);return true;}
  setVisible(value:boolean):void{this.group.visible=value;}
  update(delta:number):void{this.elapsed+=delta;this.syncVisuals();const torso=this.parts.get('torso')!.body.translation();this.maxDistance=Math.max(this.maxDistance,Math.hypot(torso.x-this.origin.x,torso.z-this.origin.z));if(this.state===AnimalState.Idle)this.parts.get('head')!.visual.rotation.y=Math.sin(this.elapsed*1.35+this.origin.x)*.055;if(this.state===AnimalState.Ragdoll&&this.elapsed-this.ragdollAt>GAME_PHYSICS.settleDelay){let speed=0;for(const part of this.parts.values()){const v=part.body.linvel();speed+=Math.hypot(v.x,v.y,v.z);}if(speed/this.parts.size<GAME_PHYSICS.settleSpeed||this.elapsed-this.ragdollAt>6)this.state=AnimalState.KnockedOut;}}
  private syncVisuals():void{for(const{visual,body}of this.parts.values()){const p=body.translation(),q=body.rotation();visual.position.set(p.x,p.y,p.z);visual.quaternion.set(q.x,q.y,q.z,q.w);}}
  destroy():void{for(const joint of this.joints)this.world.removeImpulseJoint(joint,false);for(const part of this.parts.values())this.world.removeRigidBody(part.body);this.scene.remove(this.group);this.group.traverse(o=>{if(o instanceof THREE.Mesh)o.geometry.dispose();});this.materials.forEach(m=>m.dispose());this.targets.length=0;this.parts.clear();this.colliders.clear();}
}
