import { type AnimalPartName, AnimalState } from '../entities/AnimalDefinition'; import { Fist } from '../entities/Fist'; import type { RagdollAnimal } from '../entities/RagdollAnimal'; import { RaycastController, type PointerRay } from '../input/RaycastController'; import { Effects } from '../effects/Effects'; import type { EnvironmentManager } from '../environment/EnvironmentManager'; import type { Destructible } from '../environment/Destructible'; import type { ComboSystem } from '../systems/ComboSystem'; import type { ScoreSystem } from '../systems/ScoreSystem';
export class PunchSystem {
  bonks=0;lastPart='none';lastImpulse=0;enabled=true;private cooldownUntil=0;private contextVersion=0;private animals:RagdollAnimal[]=[];private environment?:EnvironmentManager;
  get score():number{return this.scoring.total;}
  constructor(private input:RaycastController,private fist:Fist,private effects:Effects,private combo:ComboSystem,private scoring:ScoreSystem,private onImpact:(label:string)=>void,private onHitStop:()=>void){}
  setContext(animals:RagdollAnimal[],environment:EnvironmentManager):void{this.contextVersion++;this.animals=animals;this.environment=environment;this.bonks=0;this.lastPart='none';this.lastImpulse=0;this.enabled=true;this.scoring.reset();this.combo.reset();}
  addScore(points:number):void{this.scoring.add(points);}
  handle(pointer:PointerRay):void{
    if(!this.enabled||!this.environment||performance.now()<this.cooldownUntil)return;this.input.setRay(pointer.ray);const animals=this.animals.filter(a=>a.visible&&a.state===AnimalState.Idle);const targets=[...this.environment.targets,...animals.flatMap(a=>a.targets)];const hit=this.input.intersect(targets);if(!hit)return;
    const partName=hit.object.userData.animalPart as AnimalPartName|undefined;const animal=hit.object.userData.animal as RagdollAnimal|undefined;const destructible=hit.object.userData.destructible as Destructible|undefined;const point=hit.point.clone(),direction=pointer.ray.direction.clone();if((!partName||!animal)&&!destructible)return;this.lastPart=partName??'object';const version=this.contextVersion;
    if(!this.fist.punch(point,()=>{if(version!==this.contextVersion)return;let points=0,label='BONK!',critical=false;if(partName&&animal){const base=partName==='head'?150:partName.includes('Leg')?90:110;const chain=this.combo.start(`player:${animal.instanceId}`,base);points=animal.hit(partName,point,direction,chain);label=partName==='head'?'HEAD BONK!':partName.includes('Leg')?'TRIP BONK!':'BONK!';critical=partName==='head';}else{const result=destructible!.hit(point,direction.clone());points=result.score;this.combo.start(`object:${this.bonks}`,points);label=result.label;critical=result.broken;}this.lastImpulse=points;this.bonks++;this.onImpact(label);this.onHitStop();this.effects.impact(point,pointer.x,pointer.y,label,critical);},()=>undefined))return;this.cooldownUntil=performance.now()+this.fist.definition.cooldown;
  }
}
