import * as THREE from 'three'; import RAPIER from '@dimforge/rapier3d-compat'; import type { PhysicsWorld } from '../physics/PhysicsWorld'; import type { Destructible, DestructionResult } from './Destructible';
interface Brick { mesh: THREE.Mesh; body: RAPIER.RigidBody; collider: RAPIER.Collider; }
export class BreakableWall implements Destructible {
  readonly targets: THREE.Mesh[] = []; broken = false; private bricks: Brick[] = []; private health = 95; private expires = 0;
  private readonly geometry = new THREE.BoxGeometry(.78, .38, .34); private readonly materials = [0xc9543d, 0xdf6a4c, 0xb94435].map(color => new THREE.MeshStandardMaterial({ color, roughness: .88 }));
  constructor(private scene: THREE.Scene, private physics: PhysicsWorld, private onBreak: () => void) {
    for (let row = 0; row < 6; row++) for (let col = 0; col < 5; col++) { const x = (col - 2) * .79 + (row % 2 ? .2 : -.2); const y = .2 + row * .39; const z = 1.05; const mesh = new THREE.Mesh(this.geometry, this.materials[(row + col) % this.materials.length]); mesh.position.set(x, y, z); mesh.castShadow = true; mesh.receiveShadow = true; mesh.userData.targetKind = 'destructible'; mesh.userData.destructible = this; this.scene.add(mesh); this.targets.push(mesh); const body = physics.world.createRigidBody(RAPIER.RigidBodyDesc.fixed().setTranslation(x, y, z).setLinearDamping(.5).setAngularDamping(.6)); const collider = physics.world.createCollider(RAPIER.ColliderDesc.cuboid(.385, .185, .165).setDensity(.9).setFriction(.82).setRestitution(.25), body); this.bricks.push({ mesh, body, collider }); }
  }
  hit(point: THREE.Vector3, direction: THREE.Vector3, power = 55): DestructionResult { if (this.broken) return { broken: false, score: 0, label: '' }; this.health -= power; if (this.health > 0) { const nearest = this.bricks.reduce((best, brick) => brick.mesh.position.distanceTo(point) < best.mesh.position.distanceTo(point) ? brick : best); nearest.mesh.scale.set(.9, .9, .9); return { broken: false, score: 40, label: 'CRACK!' }; } return this.break(direction, point); }
  collision(): DestructionResult { return { broken: false, score: 0, label: '' }; }
  private break(direction: THREE.Vector3, point: THREE.Vector3): DestructionResult { this.broken = true; this.targets.length = 0; this.expires = performance.now() + 6000; for (const brick of this.bricks) { brick.mesh.userData.targetKind = undefined; brick.body.setBodyType(RAPIER.RigidBodyType.Dynamic, true); const distance = Math.max(.45, brick.mesh.position.distanceTo(point)); brick.body.applyImpulse({ x: direction.x * 1.2 / distance + THREE.MathUtils.randFloatSpread(.45), y: THREE.MathUtils.randFloat(.35, 1.2), z: direction.z * 1.2 / distance }, true); brick.body.applyTorqueImpulse({ x: Math.random(), y: Math.random(), z: Math.random() }, true); } this.onBreak(); return { broken: true, score: 300, label: 'WALL SMASH!' }; }
  update(): void { if (!this.broken) return; for (const brick of this.bricks) { const p = brick.body.translation(), q = brick.body.rotation(); brick.mesh.position.set(p.x, p.y, p.z); brick.mesh.quaternion.set(q.x, q.y, q.z, q.w); } if (this.expires && performance.now() >= this.expires) { for (const brick of [...this.bricks]) this.removeBrick(brick); this.expires = 0; } }
  private removeBrick(brick: Brick): void { this.physics.world.removeRigidBody(brick.body); this.scene.remove(brick.mesh); this.bricks.splice(this.bricks.indexOf(brick), 1); }
  destroy(): void { for (const brick of [...this.bricks]) this.removeBrick(brick); this.targets.length = 0; this.geometry.dispose(); this.materials.forEach(material => material.dispose()); }
}
