import * as THREE from 'three'; import RAPIER from '@dimforge/rapier3d-compat'; import type { PhysicsWorld, ContactImpact } from '../physics/PhysicsWorld'; import type { Destructible, DestructionResult } from './Destructible'; import { DebrisManager } from './DebrisManager';
export type PropType = 'crate' | 'barrel';
export class PhysicsProp implements Destructible {
  readonly targets: THREE.Mesh[] = []; broken = false; private mesh: THREE.Mesh; private body: RAPIER.RigidBody; private collider: RAPIER.Collider; private health: number; private lastCollision = 0;
  constructor(private scene: THREE.Scene, private physics: PhysicsWorld, private debris: DebrisManager, readonly type: PropType, position: [number, number, number], private canBreak = true, private onPhysicsImpact?: (prop:PhysicsProp,result:DestructionResult,impact:ContactImpact)=>void) {
    const crate = type === 'crate'; this.health = crate ? 70 : 95; const geometry = crate ? new THREE.BoxGeometry(.9, .9, .9, 1, 1, 1) : new THREE.CylinderGeometry(.42, .48, 1.1, 14); const material = new THREE.MeshStandardMaterial({ color: crate ? 0xbd783d : 0x3b82a8, roughness: .82, metalness: crate ? 0 : .18 }); this.mesh = new THREE.Mesh(geometry, material); this.mesh.position.set(...position); this.mesh.castShadow = true; this.mesh.receiveShadow = true; this.mesh.userData.targetKind = 'destructible'; this.mesh.userData.destructible = this; this.scene.add(this.mesh); this.targets.push(this.mesh);
    this.body = physics.world.createRigidBody(RAPIER.RigidBodyDesc.dynamic().setTranslation(...position).setLinearDamping(.45).setAngularDamping(.55)); const desc = crate ? RAPIER.ColliderDesc.cuboid(.45, .45, .45) : RAPIER.ColliderDesc.cylinder(.55, .44); this.collider = physics.world.createCollider(desc.setDensity(crate ? 1.2 : 1.6).setFriction(.85).setRestitution(crate ? .22 : .42), this.body); physics.registerImpact(this.collider, impact => {const result=this.collision(impact.force);this.onPhysicsImpact?.(this,result,impact);});
    if (crate) this.addCrateDetails(); else this.addBarrelDetails();
  }
  private addCrateDetails(): void { const edge = new THREE.LineSegments(new THREE.EdgesGeometry(this.mesh.geometry), new THREE.LineBasicMaterial({ color: 0x6f3d20, linewidth: 2 })); this.mesh.add(edge); }
  private addBarrelDetails(): void { for (const y of [-.34, .34]) { const band = new THREE.Mesh(new THREE.TorusGeometry(.445, .045, 6, 18), new THREE.MeshStandardMaterial({ color: 0x172033, metalness: .45, roughness: .5 })); band.rotation.x = Math.PI / 2; band.position.y = y; this.mesh.add(band); } }
  hit(_point: THREE.Vector3, direction: THREE.Vector3, power = 42): DestructionResult { if (this.broken) return { broken: false, score: 0, label: '' }; this.body.applyImpulse({ x: direction.x * 2.8, y: Math.max(.8, direction.y * 2.4), z: direction.z * 2.8 }, true); this.health -= power; return this.health <= 0 && this.canBreak ? this.break(direction) : { broken: false, score: 25, label: this.type === 'crate' ? 'THUNK!' : 'CLANG!' }; }
  collision(force: number): DestructionResult { const now = performance.now(); if (this.broken || !this.canBreak || force < 90 || now - this.lastCollision < 350) return { broken: false, score: 0, label: '' }; this.lastCollision = now; this.health -= Math.min(55, force * .08); return this.health <= 0 ? this.break(new THREE.Vector3(0, .4, -1)) : { broken: false, score: 0, label: '' }; }
  private break(direction: THREE.Vector3): DestructionResult { if (this.broken) return { broken: false, score: 0, label: '' }; this.broken = true; this.physics.unregisterImpact(this.collider); const position = this.mesh.position.clone(); this.scene.remove(this.mesh); this.physics.world.removeRigidBody(this.body); this.targets.length = 0; this.debris.spawn(position, this.type === 'crate' ? 0xbd783d : 0x3b82a8, this.type === 'crate' ? 8 : 6, direction.multiplyScalar(3)); return { broken: true, score: this.type === 'crate' ? 150 : 180, label: this.type === 'crate' ? 'CRATE SMASH!' : 'BARREL BASH!' }; }
  update(): void { if (this.broken) return; const p = this.body.translation(), q = this.body.rotation(); this.mesh.position.set(p.x, p.y, p.z); this.mesh.quaternion.set(q.x, q.y, q.z, q.w); }
  get id():string{return `${this.type}:${this.collider.handle}`;}
  destroy(): void { if (!this.broken) { this.physics.unregisterImpact(this.collider); this.physics.world.removeRigidBody(this.body); this.scene.remove(this.mesh); } this.targets.length = 0; this.mesh.traverse(object => { if (object instanceof THREE.Mesh || object instanceof THREE.LineSegments) { object.geometry.dispose(); const materials = Array.isArray(object.material) ? object.material : [object.material]; materials.forEach(material => material.dispose()); } }); }
}
